# See readme for details on setting harness_host
harness_host: "harness.lab.tsew.net"
listen_port: "443"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/proxy-body-size: "2g"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ""  # Uses harness_host from above if not specified
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: harness-tls
      hosts:
        - ""  # Uses harness_host from above if not specified

# Add custom annotations/labels for deployments
deployment:
  annotations:
    # name: value
  labels:
    # name: value

# Add custom annotations/labels for pods/replicas
replica:
  annotations:
    # name: value
  labels:
    # name: value

# Add custom annotations/labels for pods/replicas
service:
  annotations:
  # name: value
  labels:
  # name: value

# Add custom annotations/labels for service accounts
serviceAccount:
  annotations:
  # name: value
  labels:
  # name: value

# Add custom annotations/labels for config maps
configMap:
  annotations:
  # name: value
  labels:
  # name: value

# Add custom annotations/labels for secrets
secret:
  annotations:
  # name: value
  labels:
  # name: value

# Harness application versions
versions:
  busybox: 1.35.0
  log_service: release-70-ubi
  manager: 79421
  mongo: 4.4.19
  ng_auth_ui: 1.7.0
  ng_ui: 0.356.12
  nginx: 1.21.4
  redis: 6.2.7-alpine
  scm: release-150-ubi
  platform_service: 79202
  delegate_proxy: 79310
  pipeline_service: 1.33.8

# Resource request & limit configuration per application
ng_ui:
  resources:
    limits:
      memory: 32Mi
      cpu: 200m
    requests:
      memory: 32Mi
      cpu: 200m

ng_auth_ui:
  resources:
    limits:
      memory: 24Mi
      cpu: 200m
    requests:
      memory: 24Mi
      cpu: 200m

manager:
  config:
    memory: 232
  resources:
    limits:
      memory: 780Mi
      cpu: 1
    requests:
      memory: 512Mi
      cpu: 200m

ng_manager:
  config:
    memory: 296
  resources:
    limits:
      memory: 816Mi
      cpu: 1
    requests:
      memory: 512Mi
      cpu: 200m

pipeline:
  config:
    memory: 200
  resources:
    limits:
      memory: 1000Mi
      cpu: 1
    requests:
      memory: 512Mi
      cpu: 200m

platform:
  config:
    memory: 200
  resources:
    limits:
      memory: 300Mi
      cpu: 1
    requests:
      memory: 300Mi
      cpu: 200m

log_service:
  resources:
    limits:
      memory: 72Mi
      cpu: 200m
    requests:
      memory: 72Mi
      cpu: 200m

scm:
  resources:
    limits:
      memory: 100Mi
      cpu: 200m
    requests:
      memory: 100Mi
      cpu: 200m

delegate_proxy:
  resources:
    limits:
      memory: 24Mi
      cpu: 200m
    requests:
      memory: 24Mi
      cpu: 200m

proxy:
  resources:
    limits:
      memory: 100Mi
      cpu: 200m
    requests:
      memory: 100Mi
      cpu: 200m

redis:
  resources:
    limits:
      memory: 128Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 200m

mongo:
  resources:
    limits:
      memory: 320Mi
      cpu: 500m
    requests:
      memory: 320Mi
      cpu: 200m
      storage: 2Gi
      wiredTigerCacheSize: 0.125
